# Generated by Django 5.1.2 on 2025-02-25 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('billing_address', models.TextField()),
                ('tracking_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.weight')),
            ],
        ),
    ]
